### ISSUE TITLE
NIR field in point-cloud message

### ISSUE THREAD

**Issue by ilansmolySR** [ouster-lidar/ouster-ros#354]
**Is your feature request related to a problem? Please describe.**
In the point-cloud messages published by ouster-ros driver, there is no NIR field. 

**Describe the solution you'd like**
NIR field in point-cloud message.

**Describe alternatives you've considered**
The only alternative is to extract it from the nearir_image topic.

**Comment by Samahu** [comment]
Hi @ilansmolySR, the driver does publish the nearir image. Due to historical reasons it is named as `ambient` within the original **ouster_ros::Point**. If you configure your point to `native` as described in the [Point Cloud Customization](https://github.com/ouster-lidar/ouster-ros/discussions/260) feature. Then the driver maintains the original name but when using `native` the point type fields will change based on the current UDP Lidar Profile.

Closing this request since it is already fulfilled but let me know if you have any questions.
