### ISSUE TITLE
Automotive-slave ptp profile does not fidn grand master clock

### ISSUE THREAD

**Issue by Donecle** [ouster-lidar/ouster-ros#39]
Hello,

We are currently syncing our sensor with the default-relaxed profile.
We would like to switch to the automotive-slave profile, but we can't get it to sync properly.
/api/v1/time/ptp shows the profile is correctly set to automotive-slave , but gm_present is false.

Our ptp master client is ptp4l version 3.1.1 and we added the following config to the default ptp config file (inspired from https://github.com/richardcochran/linuxptp/blob/v3.1.1/configs/automotive-master.cfg)

```
BMCA			noop
masterOnly		1
inhibit_announce	1
asCapable               true
inhibit_delay_req       1
```

Does anyone have a working ptp4l config file with the automotive profile? Thanks!

**Comment by Samahu** [comment]
Hi @Donecle, Thanks for contacting us but this question is more of support question about the sensor rather than a code problem that you are facing, I recommend that you to reach to [ouster customer support](https://ouster.atlassian.net/servicedesk/customer/portal/8/group/-1) and they'd be happy to assist with that.
